/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRedesRouteImport } from './routes/_authenticated/redes'
import { Route as AuthenticatedMesasRouteImport } from './routes/_authenticated/mesas'
import { Route as AuthenticatedMembrosRouteImport } from './routes/_authenticated/membros'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMinisteriosIndexRouteImport } from './routes/_authenticated/ministerios.index'
import { Route as AuthenticatedMinisteriosSlugRouteImport } from './routes/_authenticated/ministerios.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRedesRoute = AuthenticatedRedesRouteImport.update({
  id: '/redes',
  path: '/redes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesasRoute = AuthenticatedMesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembrosRoute = AuthenticatedMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinisteriosIndexRoute =
  AuthenticatedMinisteriosIndexRouteImport.update({
    id: '/ministerios/',
    path: '/ministerios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinisteriosSlugRoute =
  AuthenticatedMinisteriosSlugRouteImport.update({
    id: '/ministerios/$slug',
    path: '/ministerios/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/membros': typeof AuthenticatedMembrosRoute
  '/mesas': typeof AuthenticatedMesasRoute
  '/redes': typeof AuthenticatedRedesRoute
  '/ministerios/$slug': typeof AuthenticatedMinisteriosSlugRoute
  '/ministerios/': typeof AuthenticatedMinisteriosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/membros': typeof AuthenticatedMembrosRoute
  '/mesas': typeof AuthenticatedMesasRoute
  '/redes': typeof AuthenticatedRedesRoute
  '/ministerios/$slug': typeof AuthenticatedMinisteriosSlugRoute
  '/ministerios': typeof AuthenticatedMinisteriosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/membros': typeof AuthenticatedMembrosRoute
  '/_authenticated/mesas': typeof AuthenticatedMesasRoute
  '/_authenticated/redes': typeof AuthenticatedRedesRoute
  '/_authenticated/ministerios/$slug': typeof AuthenticatedMinisteriosSlugRoute
  '/_authenticated/ministerios/': typeof AuthenticatedMinisteriosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/membros'
    | '/mesas'
    | '/redes'
    | '/ministerios/$slug'
    | '/ministerios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/membros'
    | '/mesas'
    | '/redes'
    | '/ministerios/$slug'
    | '/ministerios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/membros'
    | '/_authenticated/mesas'
    | '/_authenticated/redes'
    | '/_authenticated/ministerios/$slug'
    | '/_authenticated/ministerios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/redes': {
      id: '/_authenticated/redes'
      path: '/redes'
      fullPath: '/redes'
      preLoaderRoute: typeof AuthenticatedRedesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mesas': {
      id: '/_authenticated/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof AuthenticatedMesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membros': {
      id: '/_authenticated/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof AuthenticatedMembrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ministerios/': {
      id: '/_authenticated/ministerios/'
      path: '/ministerios'
      fullPath: '/ministerios/'
      preLoaderRoute: typeof AuthenticatedMinisteriosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ministerios/$slug': {
      id: '/_authenticated/ministerios/$slug'
      path: '/ministerios/$slug'
      fullPath: '/ministerios/$slug'
      preLoaderRoute: typeof AuthenticatedMinisteriosSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMembrosRoute: typeof AuthenticatedMembrosRoute
  AuthenticatedMesasRoute: typeof AuthenticatedMesasRoute
  AuthenticatedRedesRoute: typeof AuthenticatedRedesRoute
  AuthenticatedMinisteriosSlugRoute: typeof AuthenticatedMinisteriosSlugRoute
  AuthenticatedMinisteriosIndexRoute: typeof AuthenticatedMinisteriosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMembrosRoute: AuthenticatedMembrosRoute,
  AuthenticatedMesasRoute: AuthenticatedMesasRoute,
  AuthenticatedRedesRoute: AuthenticatedRedesRoute,
  AuthenticatedMinisteriosSlugRoute: AuthenticatedMinisteriosSlugRoute,
  AuthenticatedMinisteriosIndexRoute: AuthenticatedMinisteriosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
