/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfigVercelRouteImport } from './routes/config-vercel'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KidsVisitanteRouteImport } from './routes/kids.visitante'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedRedesRouteImport } from './routes/_authenticated/redes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNoticiasRouteImport } from './routes/_authenticated/noticias'
import { Route as AuthenticatedMidiaRouteImport } from './routes/_authenticated/midia'
import { Route as AuthenticatedMesasRouteImport } from './routes/_authenticated/mesas'
import { Route as AuthenticatedMembrosRouteImport } from './routes/_authenticated/membros'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedLouvorRouteImport } from './routes/_authenticated/louvor'
import { Route as AuthenticatedLivrariaRouteImport } from './routes/_authenticated/livraria'
import { Route as AuthenticatedKidsRouteImport } from './routes/_authenticated/kids'
import { Route as AuthenticatedIgrejasRouteImport } from './routes/_authenticated/igrejas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCantinaRouteImport } from './routes/_authenticated/cantina'
import { Route as AuthenticatedAvisosRouteImport } from './routes/_authenticated/avisos'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedMinisteriosIndexRouteImport } from './routes/_authenticated/ministerios.index'
import { Route as ApiPublicSmsWhatsappRouteImport } from './routes/api/public/sms-whatsapp'
import { Route as ApiPublicNotificationsRouteImport } from './routes/api/public/notifications'
import { Route as ApiPublicKidsVisitorRouteImport } from './routes/api/public/kids-visitor'
import { Route as AuthenticatedMinisteriosSlugRouteImport } from './routes/_authenticated/ministerios.$slug'
import { Route as AuthenticatedKidsRelatoriosRouteImport } from './routes/_authenticated/kids.relatorios'
import { Route as AuthenticatedKidsRetiradaCheckinIdRouteImport } from './routes/_authenticated/kids-retirada.$checkinId'

const ConfigVercelRoute = ConfigVercelRouteImport.update({
  id: '/config-vercel',
  path: '/config-vercel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsVisitanteRoute = KidsVisitanteRouteImport.update({
  id: '/kids/visitante',
  path: '/kids/visitante',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedRedesRoute = AuthenticatedRedesRouteImport.update({
  id: '/redes',
  path: '/redes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNoticiasRoute = AuthenticatedNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMidiaRoute = AuthenticatedMidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesasRoute = AuthenticatedMesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembrosRoute = AuthenticatedMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLouvorRoute = AuthenticatedLouvorRouteImport.update({
  id: '/louvor',
  path: '/louvor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLivrariaRoute = AuthenticatedLivrariaRouteImport.update({
  id: '/livraria',
  path: '/livraria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKidsRoute = AuthenticatedKidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIgrejasRoute = AuthenticatedIgrejasRouteImport.update({
  id: '/igrejas',
  path: '/igrejas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCantinaRoute = AuthenticatedCantinaRouteImport.update({
  id: '/cantina',
  path: '/cantina',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvisosRoute = AuthenticatedAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinisteriosIndexRoute =
  AuthenticatedMinisteriosIndexRouteImport.update({
    id: '/ministerios/',
    path: '/ministerios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSmsWhatsappRoute = ApiPublicSmsWhatsappRouteImport.update({
  id: '/api/public/sms-whatsapp',
  path: '/api/public/sms-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotificationsRoute = ApiPublicNotificationsRouteImport.update({
  id: '/api/public/notifications',
  path: '/api/public/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKidsVisitorRoute = ApiPublicKidsVisitorRouteImport.update({
  id: '/api/public/kids-visitor',
  path: '/api/public/kids-visitor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMinisteriosSlugRoute =
  AuthenticatedMinisteriosSlugRouteImport.update({
    id: '/ministerios/$slug',
    path: '/ministerios/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKidsRelatoriosRoute =
  AuthenticatedKidsRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedKidsRoute,
  } as any)
const AuthenticatedKidsRetiradaCheckinIdRoute =
  AuthenticatedKidsRetiradaCheckinIdRouteImport.update({
    id: '/kids-retirada/$checkinId',
    path: '/kids-retirada/$checkinId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/config-vercel': typeof ConfigVercelRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/cantina': typeof AuthenticatedCantinaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/igrejas': typeof AuthenticatedIgrejasRoute
  '/kids': typeof AuthenticatedKidsRouteWithChildren
  '/livraria': typeof AuthenticatedLivrariaRoute
  '/louvor': typeof AuthenticatedLouvorRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/membros': typeof AuthenticatedMembrosRoute
  '/mesas': typeof AuthenticatedMesasRoute
  '/midia': typeof AuthenticatedMidiaRoute
  '/noticias': typeof AuthenticatedNoticiasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/redes': typeof AuthenticatedRedesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/kids/visitante': typeof KidsVisitanteRoute
  '/kids-retirada/$checkinId': typeof AuthenticatedKidsRetiradaCheckinIdRoute
  '/kids/relatorios': typeof AuthenticatedKidsRelatoriosRoute
  '/ministerios/$slug': typeof AuthenticatedMinisteriosSlugRoute
  '/api/public/kids-visitor': typeof ApiPublicKidsVisitorRoute
  '/api/public/notifications': typeof ApiPublicNotificationsRoute
  '/api/public/sms-whatsapp': typeof ApiPublicSmsWhatsappRoute
  '/ministerios/': typeof AuthenticatedMinisteriosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/config-vercel': typeof ConfigVercelRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/cantina': typeof AuthenticatedCantinaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/igrejas': typeof AuthenticatedIgrejasRoute
  '/kids': typeof AuthenticatedKidsRouteWithChildren
  '/livraria': typeof AuthenticatedLivrariaRoute
  '/louvor': typeof AuthenticatedLouvorRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/membros': typeof AuthenticatedMembrosRoute
  '/mesas': typeof AuthenticatedMesasRoute
  '/midia': typeof AuthenticatedMidiaRoute
  '/noticias': typeof AuthenticatedNoticiasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/redes': typeof AuthenticatedRedesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/kids/visitante': typeof KidsVisitanteRoute
  '/kids-retirada/$checkinId': typeof AuthenticatedKidsRetiradaCheckinIdRoute
  '/kids/relatorios': typeof AuthenticatedKidsRelatoriosRoute
  '/ministerios/$slug': typeof AuthenticatedMinisteriosSlugRoute
  '/api/public/kids-visitor': typeof ApiPublicKidsVisitorRoute
  '/api/public/notifications': typeof ApiPublicNotificationsRoute
  '/api/public/sms-whatsapp': typeof ApiPublicSmsWhatsappRoute
  '/ministerios': typeof AuthenticatedMinisteriosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/config-vercel': typeof ConfigVercelRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/avisos': typeof AuthenticatedAvisosRoute
  '/_authenticated/cantina': typeof AuthenticatedCantinaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/igrejas': typeof AuthenticatedIgrejasRoute
  '/_authenticated/kids': typeof AuthenticatedKidsRouteWithChildren
  '/_authenticated/livraria': typeof AuthenticatedLivrariaRoute
  '/_authenticated/louvor': typeof AuthenticatedLouvorRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/membros': typeof AuthenticatedMembrosRoute
  '/_authenticated/mesas': typeof AuthenticatedMesasRoute
  '/_authenticated/midia': typeof AuthenticatedMidiaRoute
  '/_authenticated/noticias': typeof AuthenticatedNoticiasRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/redes': typeof AuthenticatedRedesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/kids/visitante': typeof KidsVisitanteRoute
  '/_authenticated/kids-retirada/$checkinId': typeof AuthenticatedKidsRetiradaCheckinIdRoute
  '/_authenticated/kids/relatorios': typeof AuthenticatedKidsRelatoriosRoute
  '/_authenticated/ministerios/$slug': typeof AuthenticatedMinisteriosSlugRoute
  '/api/public/kids-visitor': typeof ApiPublicKidsVisitorRoute
  '/api/public/notifications': typeof ApiPublicNotificationsRoute
  '/api/public/sms-whatsapp': typeof ApiPublicSmsWhatsappRoute
  '/_authenticated/ministerios/': typeof AuthenticatedMinisteriosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/config-vercel'
    | '/agenda'
    | '/avisos'
    | '/cantina'
    | '/dashboard'
    | '/igrejas'
    | '/kids'
    | '/livraria'
    | '/louvor'
    | '/mapa'
    | '/membros'
    | '/mesas'
    | '/midia'
    | '/noticias'
    | '/onboarding'
    | '/perfil'
    | '/redes'
    | '/auth/callback'
    | '/kids/visitante'
    | '/kids-retirada/$checkinId'
    | '/kids/relatorios'
    | '/ministerios/$slug'
    | '/api/public/kids-visitor'
    | '/api/public/notifications'
    | '/api/public/sms-whatsapp'
    | '/ministerios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/config-vercel'
    | '/agenda'
    | '/avisos'
    | '/cantina'
    | '/dashboard'
    | '/igrejas'
    | '/kids'
    | '/livraria'
    | '/louvor'
    | '/mapa'
    | '/membros'
    | '/mesas'
    | '/midia'
    | '/noticias'
    | '/onboarding'
    | '/perfil'
    | '/redes'
    | '/auth/callback'
    | '/kids/visitante'
    | '/kids-retirada/$checkinId'
    | '/kids/relatorios'
    | '/ministerios/$slug'
    | '/api/public/kids-visitor'
    | '/api/public/notifications'
    | '/api/public/sms-whatsapp'
    | '/ministerios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/config-vercel'
    | '/_authenticated/agenda'
    | '/_authenticated/avisos'
    | '/_authenticated/cantina'
    | '/_authenticated/dashboard'
    | '/_authenticated/igrejas'
    | '/_authenticated/kids'
    | '/_authenticated/livraria'
    | '/_authenticated/louvor'
    | '/_authenticated/mapa'
    | '/_authenticated/membros'
    | '/_authenticated/mesas'
    | '/_authenticated/midia'
    | '/_authenticated/noticias'
    | '/_authenticated/onboarding'
    | '/_authenticated/perfil'
    | '/_authenticated/redes'
    | '/auth/callback'
    | '/kids/visitante'
    | '/_authenticated/kids-retirada/$checkinId'
    | '/_authenticated/kids/relatorios'
    | '/_authenticated/ministerios/$slug'
    | '/api/public/kids-visitor'
    | '/api/public/notifications'
    | '/api/public/sms-whatsapp'
    | '/_authenticated/ministerios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ConfigVercelRoute: typeof ConfigVercelRoute
  KidsVisitanteRoute: typeof KidsVisitanteRoute
  ApiPublicKidsVisitorRoute: typeof ApiPublicKidsVisitorRoute
  ApiPublicNotificationsRoute: typeof ApiPublicNotificationsRoute
  ApiPublicSmsWhatsappRoute: typeof ApiPublicSmsWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/config-vercel': {
      id: '/config-vercel'
      path: '/config-vercel'
      fullPath: '/config-vercel'
      preLoaderRoute: typeof ConfigVercelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/visitante': {
      id: '/kids/visitante'
      path: '/kids/visitante'
      fullPath: '/kids/visitante'
      preLoaderRoute: typeof KidsVisitanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/redes': {
      id: '/_authenticated/redes'
      path: '/redes'
      fullPath: '/redes'
      preLoaderRoute: typeof AuthenticatedRedesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/noticias': {
      id: '/_authenticated/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof AuthenticatedNoticiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/midia': {
      id: '/_authenticated/midia'
      path: '/midia'
      fullPath: '/midia'
      preLoaderRoute: typeof AuthenticatedMidiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mesas': {
      id: '/_authenticated/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof AuthenticatedMesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membros': {
      id: '/_authenticated/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof AuthenticatedMembrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/louvor': {
      id: '/_authenticated/louvor'
      path: '/louvor'
      fullPath: '/louvor'
      preLoaderRoute: typeof AuthenticatedLouvorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/livraria': {
      id: '/_authenticated/livraria'
      path: '/livraria'
      fullPath: '/livraria'
      preLoaderRoute: typeof AuthenticatedLivrariaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kids': {
      id: '/_authenticated/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof AuthenticatedKidsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/igrejas': {
      id: '/_authenticated/igrejas'
      path: '/igrejas'
      fullPath: '/igrejas'
      preLoaderRoute: typeof AuthenticatedIgrejasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cantina': {
      id: '/_authenticated/cantina'
      path: '/cantina'
      fullPath: '/cantina'
      preLoaderRoute: typeof AuthenticatedCantinaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avisos': {
      id: '/_authenticated/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AuthenticatedAvisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ministerios/': {
      id: '/_authenticated/ministerios/'
      path: '/ministerios'
      fullPath: '/ministerios/'
      preLoaderRoute: typeof AuthenticatedMinisteriosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sms-whatsapp': {
      id: '/api/public/sms-whatsapp'
      path: '/api/public/sms-whatsapp'
      fullPath: '/api/public/sms-whatsapp'
      preLoaderRoute: typeof ApiPublicSmsWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notifications': {
      id: '/api/public/notifications'
      path: '/api/public/notifications'
      fullPath: '/api/public/notifications'
      preLoaderRoute: typeof ApiPublicNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kids-visitor': {
      id: '/api/public/kids-visitor'
      path: '/api/public/kids-visitor'
      fullPath: '/api/public/kids-visitor'
      preLoaderRoute: typeof ApiPublicKidsVisitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ministerios/$slug': {
      id: '/_authenticated/ministerios/$slug'
      path: '/ministerios/$slug'
      fullPath: '/ministerios/$slug'
      preLoaderRoute: typeof AuthenticatedMinisteriosSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kids/relatorios': {
      id: '/_authenticated/kids/relatorios'
      path: '/relatorios'
      fullPath: '/kids/relatorios'
      preLoaderRoute: typeof AuthenticatedKidsRelatoriosRouteImport
      parentRoute: typeof AuthenticatedKidsRoute
    }
    '/_authenticated/kids-retirada/$checkinId': {
      id: '/_authenticated/kids-retirada/$checkinId'
      path: '/kids-retirada/$checkinId'
      fullPath: '/kids-retirada/$checkinId'
      preLoaderRoute: typeof AuthenticatedKidsRetiradaCheckinIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedKidsRouteChildren {
  AuthenticatedKidsRelatoriosRoute: typeof AuthenticatedKidsRelatoriosRoute
}

const AuthenticatedKidsRouteChildren: AuthenticatedKidsRouteChildren = {
  AuthenticatedKidsRelatoriosRoute: AuthenticatedKidsRelatoriosRoute,
}

const AuthenticatedKidsRouteWithChildren =
  AuthenticatedKidsRoute._addFileChildren(AuthenticatedKidsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAvisosRoute: typeof AuthenticatedAvisosRoute
  AuthenticatedCantinaRoute: typeof AuthenticatedCantinaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIgrejasRoute: typeof AuthenticatedIgrejasRoute
  AuthenticatedKidsRoute: typeof AuthenticatedKidsRouteWithChildren
  AuthenticatedLivrariaRoute: typeof AuthenticatedLivrariaRoute
  AuthenticatedLouvorRoute: typeof AuthenticatedLouvorRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedMembrosRoute: typeof AuthenticatedMembrosRoute
  AuthenticatedMesasRoute: typeof AuthenticatedMesasRoute
  AuthenticatedMidiaRoute: typeof AuthenticatedMidiaRoute
  AuthenticatedNoticiasRoute: typeof AuthenticatedNoticiasRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRedesRoute: typeof AuthenticatedRedesRoute
  AuthenticatedKidsRetiradaCheckinIdRoute: typeof AuthenticatedKidsRetiradaCheckinIdRoute
  AuthenticatedMinisteriosSlugRoute: typeof AuthenticatedMinisteriosSlugRoute
  AuthenticatedMinisteriosIndexRoute: typeof AuthenticatedMinisteriosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAvisosRoute: AuthenticatedAvisosRoute,
  AuthenticatedCantinaRoute: AuthenticatedCantinaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIgrejasRoute: AuthenticatedIgrejasRoute,
  AuthenticatedKidsRoute: AuthenticatedKidsRouteWithChildren,
  AuthenticatedLivrariaRoute: AuthenticatedLivrariaRoute,
  AuthenticatedLouvorRoute: AuthenticatedLouvorRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedMembrosRoute: AuthenticatedMembrosRoute,
  AuthenticatedMesasRoute: AuthenticatedMesasRoute,
  AuthenticatedMidiaRoute: AuthenticatedMidiaRoute,
  AuthenticatedNoticiasRoute: AuthenticatedNoticiasRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRedesRoute: AuthenticatedRedesRoute,
  AuthenticatedKidsRetiradaCheckinIdRoute:
    AuthenticatedKidsRetiradaCheckinIdRoute,
  AuthenticatedMinisteriosSlugRoute: AuthenticatedMinisteriosSlugRoute,
  AuthenticatedMinisteriosIndexRoute: AuthenticatedMinisteriosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ConfigVercelRoute: ConfigVercelRoute,
  KidsVisitanteRoute: KidsVisitanteRoute,
  ApiPublicKidsVisitorRoute: ApiPublicKidsVisitorRoute,
  ApiPublicNotificationsRoute: ApiPublicNotificationsRoute,
  ApiPublicSmsWhatsappRoute: ApiPublicSmsWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
