ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS gender text CHECK (gender IN ('masculino','feminino')),
  ADD COLUMN IF NOT EXISTS marital_status text CHECK (marital_status IN ('solteiro','casado','viuvo','divorciado','uniao_estavel')),
  ADD COLUMN IF NOT EXISTS spouse_name text,
  ADD COLUMN IF NOT EXISTS wedding_date date,
  ADD COLUMN IF NOT EXISTS father_name text,
  ADD COLUMN IF NOT EXISTS mother_name text,
  ADD COLUMN IF NOT EXISTS profession text,
  ADD COLUMN IF NOT EXISTS education text,
  ADD COLUMN IF NOT EXISTS cpf text,
  ADD COLUMN IF NOT EXISTS rg text,
  ADD COLUMN IF NOT EXISTS zip_code text,
  ADD COLUMN IF NOT EXISTS street text,
  ADD COLUMN IF NOT EXISTS street_number text,
  ADD COLUMN IF NOT EXISTS complement text,
  ADD COLUMN IF NOT EXISTS neighborhood text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS state text,
  ADD COLUMN IF NOT EXISTS emergency_contact_name text,
  ADD COLUMN IF NOT EXISTS emergency_contact_phone text,
  ADD COLUMN IF NOT EXISTS emergency_contact_relation text,
  ADD COLUMN IF NOT EXISTS conversion_date date,
  ADD COLUMN IF NOT EXISTS baptism_date date,
  ADD COLUMN IF NOT EXISTS baptism_church text,
  ADD COLUMN IF NOT EXISTS membership_type text CHECK (membership_type IN ('batismo','transferencia','aclamacao','reconciliacao')),
  ADD COLUMN IF NOT EXISTS previous_church text,
  ADD COLUMN IF NOT EXISTS membership_status text NOT NULL DEFAULT 'ativo' CHECK (membership_status IN ('ativo','inativo','transferido','disciplina','falecido','visitante')),
  ADD COLUMN IF NOT EXISTS membership_end_date date,
  ADD COLUMN IF NOT EXISTS courses text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS gifts text,
  ADD COLUMN IF NOT EXISTS availability text,
  ADD COLUMN IF NOT EXISTS allergies text,
  ADD COLUMN IF NOT EXISTS health_notes text,
  ADD COLUMN IF NOT EXISTS blood_type text,
  ADD COLUMN IF NOT EXISTS has_children boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS children_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS notes text;

CREATE INDEX IF NOT EXISTS profiles_membership_status_idx ON public.profiles (membership_status);
CREATE INDEX IF NOT EXISTS profiles_gender_idx ON public.profiles (gender);